version: '3.9'
services:
  api:
    build: .
    command: bash -c "npm run prisma:migrate && npm run start:dev"
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - appnet

  worker:
    build: .
    command: bash -c "npm run start:worker"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - appnet

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orchestrator
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appnet

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  pgdata: